version: '2'
services:
  postgres:
    image: debezium/postgres:10.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "develop-postgres-club:1:1,topic-config:10:1,offset-storage:10:1,DVDSTORE-test-bare:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mongo:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles # --quiet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
#  neo4j:
#    image: neo4j:3.4.9
#    ports:
#     - "7474:7474"
#     - "7687:7687"
  kafkamanager:
    image: sheepkiller/kafka-manager
    ports:
     - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper
      - ZOOKEEPER_IP=zookeeper

